# Generated by Django 3.1.7 on 2021-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_commentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentenrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
            ],
        ),
    ]
