# Generated by Django 3.1.7 on 2021-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='sid',
        ),
    ]
